version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "Microsoft.CodeAnalysis"
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"
