on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # for minver
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Execute build and run tests
      run: |
        dotnet build --configuration Release /nologo
        dotnet test --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AutoConstructor
        path: artifacts/*
