on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # for minver
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Execute build
      run: |
        cd ./src/AutoConstructor.Generator
        dotnet build --configuration Release /nologo
    - name: Push to GitHub package registry
      run: dotnet nuget push .\artifacts\*.nupkg --source https://nuget.pkg.github.com/k94ll13nn3/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --no-symbols true
